apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-fuzz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-fuzz
  template:
    metadata:
      labels:
        app: sensor-fuzz
    spec:
      containers:
        - name: sensor-fuzz
          image: sensor-fuzz:latest
          ports:
            - containerPort: 8000
          env:
            - name: SF_CONFIG
              value: /app/config/config.yaml
