apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-fuzz-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-fuzz-scheduler
  template:
    metadata:
      labels:
        app: sensor-fuzz-scheduler
    spec:
      containers:
        - name: scheduler
          image: sensor-fuzz-scheduler:latest
          env:
            - name: REDIS_URL
              value: redis://redis:6379/0
          args: []
          ports:
            - containerPort: 8080
